trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'windows-latest' 

variables:
  vmIPAddress: '10.0.0.5'  
  vmUsername: 'okhalij'    
  vmPassword: '@Casanostra8'   
  deploymentFolder: 'C:\deployment'        
  artifactName: 'testartifact'
  
stages:
- stage: Build
  displayName: 'Build and Publish Artifact'
  jobs:
  - job: 'BuildAndPublish'
    displayName: 'Build .NET framework'
    steps:
    # Step 1: Install NuGet packages
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.csproj'
      displayName: 'Restore NuGet Packages'

    # Step 2: Build the application
    - task: VSBuild@1
      inputs:
        solution: '**/*.csproj'
        msbuildArgs: '/p:TargetFrameworkVersion=v4.8 /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: 'Any CPU'
        configuration: 'Release'
      displayName: 'Build Solution with .NET Framework 4.8'

    # Step 3: Publish build artifact
    - task: PublishPipelineArtifact@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: '$(artifactName)'  
      displayName: 'Publish Build Artifact'

- stage: DeployStg
  displayName: 'Deploy to staging'
  dependsOn: Build  # Ensure the Build stage completes successfully
  jobs:
  - job: DeployToVM
    displayName: 'Deploy to Windows Virtual Machine'
    steps:
      # Step 1: Download Artifact
      - download: 'current'
        artifact: '$(artifactName)'
        displayName: 'Download Artifact'

      # Step 2: Copy Files to Virtual Machine
      - task: WindowsMachineFileCopy@2
        displayName: 'Copy Files to Windows Virtual Machine'
        inputs:
          SourcePath: 'D:\a\1/testartifact'
          deploymentMethod: 'zipDeploy'
          TargetPath: '$(deploymentFolder)'
          MachineNames: '$(vmIPAddress)'
          AdminUserName: '$(vmUsername)'
          AdminPassword: '$(vmPassword)'
      
