trigger:
  branches:
    include:
      - main  

pool:
  vmImage: 'windows-latest' 

variables:
  vmIPAddress: 'YOUR_VM_IP_ADDRESS'  
  vmUsername: 'YOUR_VM_USERNAME'    
  vmPassword: 'YOUR_VM_PASSWORD'   
  deploymentFolder: 'deploy'        

steps:
  # Restore Dependencies
  - task: DotNetCoreCLI@2
    displayName: 'Restore Dependencies'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  # Build Application
  - task: DotNetCoreCLI@2
    displayName: 'Build Application'
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  # Run Tests
  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/*.csproj'

  # Publish Application
  - task: DotNetCoreCLI@2
    displayName: 'Publish Application'
    inputs:
      command: 'publish'
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

  # Copy Files to Virtual Machine
  - task: CopyFilesOverSSH@0
    displayName: 'Copy Files to Virtual Machine'
    inputs:
      sshEndpoint: 'VMConnection'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      targetFolder: 'C:\\DeploymentFolder' 

  # Run Deployment Commands on Virtual Machine
  - task: SSH@0
    displayName: 'Deploy Application on Virtual Machine'
    inputs:
      sshEndpoint: 'VMConnection'
      commands: |
        cd /home/$(vmUsername)/$(deploymentFolder)
        # Add commands to deploy/start your application, e.g.,
        # dotnet MyApp.dll for .NET applications
